### ISSUE TITLE
[lua error] Interface/AddOns/Breadcrumbs/Breadcrumbs.lua:770: attempt to concatenate upvalue 'QUEST_ICONS_FILE' (a nil value)

### ISSUE THREAD

**Issue by JourneyOver** [glassleo/Breadcrumbs#45]
Seem to randomly get this error when mousing over random quest markers on the world map. Can reproduce easily with the quest marker icon that was for the catalyst charges (the quest no longer exists at this time but the icon still remains on the world map).

```
Interface/AddOns/Breadcrumbs/Breadcrumbs.lua:770: attempt to concatenate upvalue 'QUEST_ICONS_FILE' (a nil value)
Count: 1

Call Stack:
[string "=[C]"]: ?
[string "@Interface/AddOns/Breadcrumbs/Breadcrumbs.lua"]:770: in function <Interface/AddOns/Breadcrumbs/Breadcrumbs.lua:732>
```

**Comment by glassleo** [comment]
Thanks for the report! Seems like Blizzard set the ``QUEST_ICONS_FILE`` constant to ``nil`` in patch 10.1 for some reason.

**Comment by JourneyOver** [comment]
> Thanks for the report! Seems like Blizzard set the `QUEST_ICONS_FILE` constant to `nil` in patch 10.1 for some reason.

Looks like it's working as I've been mousing over icons and so far no errors so thanks on that :D

Does look like when you went and did this commit https://github.com/glassleo/Breadcrumbs/commit/2a2826a527aa4f1d7e699fa530ab5c7a35ddb33d you missed two more lines at https://github.com/glassleo/Breadcrumbs/blob/main/Breadcrumbs/Quests.lua#L333-L334 for the weekly quest for the revival catalyst. (iirc in 10.1 when the revival catalyst opens back up there is going to be no quest for it, you'll just automatically gain a token every week instead)

Couple extra notes:

https://github.com/glassleo/Breadcrumbs/blob/main/Breadcrumbs/Quests.lua#L629 should be invalidated by `Academic Acquaintances -- quest ID 66557` (You can only do `What of the Winterpelt Clan` or `Academic Acquaintances` but you can't do both (so should probably have a check to make sure that `Academic Acquaintances` has a invalidation check if you have already completed `What of the Winterpelt Clan` as well))

https://github.com/glassleo/Breadcrumbs/blob/main/Breadcrumbs/Quests.lua#L465 should be invalidated if you have already completed `Welcome to the Assembly -- quest ID 70550` (If you complete `Welcome to the Assembly` before doing `Supporting the Cobalt Assembly` you can no longer pick up the quest)

**Comment by glassleo** [comment]
> you missed two more lines

Nice catch! Fixed.

> Academic Acquaintances

Fixed.

> Supporting the Cobalt Assembly

There was actually just typo with a missing space here for the requirements. Corrected!

**Comment by JourneyOver** [comment]
> > you missed two more lines
>
> Nice catch! Fixed.
>
> > Academic Acquaintances
>
> Fixed.
>
>> Supporting the Cobalt Assembly
>
> There was actually just typo with a missing space here for the requirements. Corrected!

Glad to see the quick fixes on these :p and haha I thought that there was a missing space there for the supporting the cobalt assembly one, but wasn't 100% sure xD

if I run into anymore random quests in the future that either need a invalidation or random fix or whatever, I'll throw up a new issue for them ^^

**Comment by glassleo** [comment]
> if I run into anymore random quests in the future that either need a invalidation or random fix or whatever, I'll throw up a new issue for them ^^

Sure thing! You can also throw up a pull request if you want anything changed :)

**Comment by JourneyOver** [comment]
@glassleo I'd rather not just open a new issue for this since it's not an issue or anything so I'll use one of my old issue threads, just mainly coming through to see if you are still working on this project?

**Comment by glassleo** [comment]
> @glassleo I'd rather not just open a new issue for this since it's not an issue or anything so I'll use one of my old issue threads, just mainly coming through to see if you are still working on this project?

I'll be honest, I haven't had much time to work on it lately (and my old computer breaking down recently did not help) but I would like to finish it some day. I have been updating some minor things, for example I think almost all Dragonflight treasures are implemented now. But yeah I haven't had the time to add more quest data in a while.

The addon itself is pretty much complete, it's just missing *a lot* of quest data.

**Comment by glassleo** [comment]
P.S. if you have any interest in helping me compile the quest data, let me know! It's not that hard but it takes a lot of time and effort.
